{{- if and .Values.envoy.enabled .Values.envoy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "imas-nats.envoy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imas-nats.labels" . | nindent 4 }}
    app.kubernetes.io/component: envoy
  {{- with .Values.envoy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
