package pki

// The imas CLI's end of sealed CLI <-> farmer traffic
// (docs/design/imas-payload-encryption-design.md, Decision A, J.1): the
// CLI box key on local disk, the pinned tenant box key and tenant ID, and
// sealing requests and opening replies with them. FLAG FOR SECURITY
// REVIEW.
//
// CLI config (~/.config/imas/imas):
//
//	cliboxprivfile  the CLI box private key, standard base64, mode 0600.
//	                Default <config dir>/imas/cli-box.key. Generated by
//	                `imas auth keygen`; it never leaves this host.
//	tenantboxpub    the tenant's box public key, standard base64, copied
//	                out of band (as the bus root CA is), never fetched
//	                over the bus.
//	tenantid        the tenant whose key that is. Every sealed message
//	                names its tenant (payloadbox.Message.TenantID), so the
//	                CLI pins it with the key, as a sprout does.
//
// A key rotation (`imas auth rotate-key`) works as the sprout's does: the
// new key is written as pending (<cliboxprivfile>.next) and submitted
// sealed under the current one; it becomes current only once a farmer
// reply opens under it, which proves farmer recorded it. A lost or
// refused submission leaves the CLI on its current key, and the next
// rotate-key resubmits the same pending key.

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/taigrr/jety"

	"github.com/yogzblr/imas/internal/auth"
	"github.com/yogzblr/imas/internal/payloadbox"
)

// CLI config keys.
const (
	CLIBoxPrivFileKey  = "cliboxprivfile"
	CLITenantBoxPubKey = "tenantboxpub"
	CLITenantIDKey     = "tenantid"
)

// ErrCLIBoxNotConfigured: the CLI has no box key, or no pinned tenant key
// or tenant ID, so it can't make a sealed request.
var ErrCLIBoxNotConfigured = errors.New("pki: the CLI has no box key or no pinned tenant (imas auth keygen; set tenantboxpub and tenantid)")

// ErrCLIBoxKeyExists: imas auth keygen found a key already there.
var ErrCLIBoxKeyExists = errors.New("pki: a CLI box key already exists; refusing to replace it (rotate it instead, or pass --force)")

var cliBoxMu sync.Mutex

// CLIBoxPrivFile is where the CLI box private key lives.
func CLIBoxPrivFile() string {
	if p := jety.GetString(CLIBoxPrivFileKey); p != "" {
		return p
	}
	dir := os.Getenv("XDG_CONFIG_HOME")
	if dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return ""
		}
		dir = filepath.Join(home, ".config")
	}
	return filepath.Join(dir, "imas", "cli-box.key")
}

func cliPendingBoxPrivFile() string { return CLIBoxPrivFile() + ".next" }

// GenerateCLIBoxKey creates a fresh CLI box key at path (mode 0600) and
// returns its public half, standard base64. An existing key is
// ErrCLIBoxKeyExists unless force, since replacing the registered key
// locks the user out until an admin registers the new one.
func GenerateCLIBoxKey(path string, force bool) (string, error) {
	if path == "" {
		return "", errors.New("pki: no CLI box key path")
	}
	cliBoxMu.Lock()
	defer cliBoxMu.Unlock()
	if _, err := os.Stat(path); err == nil && !force {
		return "", ErrCLIBoxKeyExists
	}
	pub, err := writeFreshBoxKey(path)
	if err != nil {
		return "", err
	}
	// A pending key left by a rotation of the replaced key belongs to it.
	if err := os.Remove(path + ".next"); err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("pki: removing the replaced key's pending rotation: %w", err)
	}
	return pub, nil
}

func writeFreshBoxKey(path string) (string, error) {
	var priv [32]byte
	if _, err := rand.Read(priv[:]); err != nil {
		return "", fmt.Errorf("pki: generating CLI box key: %w", err)
	}
	defer wipe(priv[:])
	pub, err := boxPubFromPriv(&priv)
	if err != nil {
		return "", err
	}
	k, _ := decodeBoxKeyHalf(pub)
	if err := payloadbox.CheckPublicKey(k); err != nil {
		return "", err
	}
	encoded := []byte(base64.StdEncoding.EncodeToString(priv[:]))
	defer wipe(encoded)
	if err := writeFileAtomic(path, encoded, 0o600); err != nil {
		return "", fmt.Errorf("pki: writing CLI box key: %w", err)
	}
	return pub, nil
}

// CLIBoxPub returns the public half of the CLI's current box key.
func CLIBoxPub() (string, error) {
	priv, err := readBoxPrivKeyFile(CLIBoxPrivFile(), false)
	if err != nil {
		if os.IsNotExist(err) {
			return "", ErrCLIBoxNotConfigured
		}
		return "", err
	}
	defer wipe(priv[:])
	return boxPubFromPriv(priv)
}

// cliKeys is everything the CLI seals and opens with.
type cliKeys struct {
	userID    string
	tenantID  string
	tenantPub *[32]byte
	current   *[32]byte
	pending   *[32]byte // nil unless a rotation is in flight
}

func (k *cliKeys) wipe() {
	for _, p := range []*[32]byte{k.current, k.pending} {
		if p != nil {
			wipe(p[:])
		}
	}
}

func loadCLIKeysLocked() (*cliKeys, error) {
	tenantID := jety.GetString(CLITenantIDKey)
	tenantPubB64 := jety.GetString(CLITenantBoxPubKey)
	if tenantID == "" || tenantPubB64 == "" || !IsValidTenantID(tenantID) {
		return nil, ErrCLIBoxNotConfigured
	}
	tenantPub, err := decodePinnedBoxPub(tenantPubB64)
	if err != nil {
		return nil, fmt.Errorf("pki: %s: %w", CLITenantBoxPubKey, err)
	}
	userID, err := auth.GetPubkey()
	if err != nil {
		return nil, err
	}
	current, err := readBoxPrivKeyFile(CLIBoxPrivFile(), false)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ErrCLIBoxNotConfigured
		}
		return nil, err
	}
	pending, err := readBoxPrivKeyFile(cliPendingBoxPrivFile(), true)
	if err != nil {
		wipe(current[:])
		return nil, err
	}
	return &cliKeys{userID: userID, tenantID: tenantID, tenantPub: tenantPub, current: current, pending: pending}, nil
}

func loadCLIKeys() (*cliKeys, error) {
	cliBoxMu.Lock()
	defer cliBoxMu.Unlock()
	return loadCLIKeysLocked()
}

// CLISealRequest seals a request for method (subject imas.api.<method>)
// under purpose, with params, from this CLI's user to the pinned tenant
// key, always with the current key. It returns the sealed envelope, the
// message ID the reply must name, and the user ID for the
// payloadbox.PrincipalHeader.
func CLISealRequest(purpose, method string, params any) (data []byte, msgID, userID string, err error) {
	keys, err := loadCLIKeys()
	if err != nil {
		return nil, "", "", err
	}
	defer keys.wipe()
	data, msgID, err = payloadbox.SealCall(payloadbox.Call{
		Purpose: purpose, TenantID: keys.tenantID, Principal: keys.userID,
		Method: method, Subject: CLIAPISubjectPrefix + method, Params: params,
	}, []payloadbox.KeyPair{{PeerPub: keys.tenantPub, Priv: keys.current}})
	return data, msgID, keys.userID, err
}

// CLIOpenReply opens farmer's sealed reply to the request reqID for
// method, trying the current key and then a pending one. If it opened
// under the pending key, that key is promoted to current (farmer only
// seals to a key it recorded). Any failure to open is payloadbox.ErrOpen.
func CLIOpenReply(method, reqID string, data []byte) (*payloadbox.ReplyBody, error) {
	keys, err := loadCLIKeys()
	if err != nil {
		return nil, err
	}
	defer keys.wipe()
	want := payloadbox.ReplyExpect{
		Purpose: payloadbox.PurposeCLIReply, TenantID: keys.tenantID, Principal: keys.userID,
		ReplyTo: reqID, Method: method, Subject: CLIAPISubjectPrefix + method,
	}
	for _, priv := range []*[32]byte{keys.current, keys.pending} {
		if priv == nil {
			continue
		}
		_, body, err := payloadbox.OpenReply(data, []payloadbox.KeyPair{{PeerPub: keys.tenantPub, Priv: priv}}, want)
		if err != nil {
			continue
		}
		if priv == keys.pending {
			pub, err := boxPubFromPriv(priv)
			if err != nil {
				return nil, err
			}
			if err := PromoteCLIBoxKey(pub); err != nil {
				return nil, err
			}
		}
		return body, nil
	}
	return nil, payloadbox.ErrOpen
}

// BeginCLIBoxKeyRotation makes (or reuses) the pending CLI box key and
// returns a c2f.userkey.pub request naming its public half, sealed under
// the current key, for MethodAuthRotateKey.
func BeginCLIBoxKeyRotation() (data []byte, msgID, userID, newPub string, err error) {
	cliBoxMu.Lock()
	pendingPath := cliPendingBoxPrivFile()
	pending, err := readBoxPrivKeyFile(pendingPath, true)
	if err == nil && pending == nil {
		_, err = writeFreshBoxKey(pendingPath)
		if err == nil {
			pending, err = readBoxPrivKeyFile(pendingPath, false)
		}
	}
	if err != nil {
		cliBoxMu.Unlock()
		return nil, "", "", "", err
	}
	newPub, err = boxPubFromPriv(pending)
	wipe(pending[:])
	cliBoxMu.Unlock()
	if err != nil {
		return nil, "", "", "", err
	}
	data, msgID, userID, err = CLISealRequest(payloadbox.PurposeCLIUserKeySubmit, MethodAuthRotateKey, cliUserKeyBody{Pub: newPub})
	return data, msgID, userID, newPub, err
}

// PromoteCLIBoxKey makes the pending key whose public half is newPub the
// current one, and destroys the old one: the CLI never needs it again
// (farmer seals replies to the active key), and a private key that isn't
// kept can't leak. A no-op if that key is no longer pending.
func PromoteCLIBoxKey(newPub string) error {
	cliBoxMu.Lock()
	defer cliBoxMu.Unlock()
	pendingPath := cliPendingBoxPrivFile()
	pending, err := readBoxPrivKeyFile(pendingPath, true)
	if err != nil || pending == nil {
		return err
	}
	pub, err := boxPubFromPriv(pending)
	wipe(pending[:])
	if err != nil || pub != newPub {
		return err
	}
	return os.Rename(pendingPath, CLIBoxPrivFile())
}
